# Generated by Django 6.1.1 on 2026-09-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='THE 52 CLUB SESSION', max_length=200)),
                ('description', models.TextField(blank=True, default='Join us for our weekly strength-based community session. Train together, push your limits and get stronger as a community.')),
                ('date_text', models.CharField(default='EVERY SUNDAY', help_text='Display text for the date (e.g., "EVERY SUNDAY", "SEP 15, 2026")', max_length=100)),
                ('time_text', models.CharField(default='7:00 AM', help_text='Display text for the time', max_length=50)),
                ('location', models.CharField(default='LOCATION ANNOUNCED WEEKLY', help_text='Update this to set the current event location', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Only active events are shown on the website')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload high-quality images (recommended: 1200x800px or larger)', upload_to='gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_visible', models.BooleanField(default=True, help_text='Only visible images are shown on the website')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('message', models.TextField(blank=True, help_text='What brings them to The 52 Club')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Registration fee in ₹ (INR)', max_digits=10)),
                ('upi_id', models.CharField(default='8374446838@ybl', help_text='UPI ID for receiving payments', max_length=100)),
                ('upi_display_name', models.CharField(default='The 52 Club', help_text='Name displayed on UPI payment screen', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
