# Generated by Django 6.1.1 on 2026-09-04 18:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='transaction_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique transaction identifier for payment tracking'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='webhook_secret',
            field=models.CharField(default='the52club-webhook-secret', help_text='Secret key for authenticating webhook requests', max_length=100),
        ),
    ]
