# Generated by Django 6.1.1 on 2026-09-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_member_transaction_id_sitesettings_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay Order ID created for this registration', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay Payment ID captured after successful payment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='razorpay_key_id',
            field=models.CharField(blank=True, default='rzp_test_52clubKeyId', help_text='Your Razorpay Key ID (from Razorpay Dashboard)', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, default='rzp_test_52clubKeySecret', help_text='Your Razorpay Key Secret', max_length=100),
        ),
    ]
