# Generated by Django 6.1.1 on 2026-09-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_member_razorpay_order_id_member_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='collaborations',
            field=models.CharField(blank=True, default='7 FINISHERS', help_text='Collaborations, partners, or event highlights', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='event_number',
            field=models.CharField(default='01', help_text='Event number display (e.g., "01", "02", "SESSION #1")', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='google_drive_link',
            field=models.URLField(blank=True, help_text='Google Drive URL for event photos/videos'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload event banner/photo', null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, default='RUNNING, CHALLENGE, COMMUNITY', help_text='Comma-separated tags (e.g., "RUNNING, CHALLENGE, COMMUNITY")', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='EDEN GARDENS TURF, ANANTAPUR', help_text='Event venue location', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_text',
            field=models.CharField(default='SUNDAY, 23RD AUGUST', help_text='Display text for the date', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='Seven challenges. One finish. The beginning of the 52 Club.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_text',
            field=models.CharField(default='6:30 AM', help_text='Display text for the time', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='SEVEN CHALLENGES — ONE FINISH', max_length=200),
        ),
    ]
