# Generated by Django 6.1.1 on 2026-09-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_remove_event_location_event_collaborations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Partner / Collaborator name (e.g., "Cult.fit", "RedBull", "Eden Gardens")', max_length=200)),
                ('category', models.CharField(default='COLLABORATIONS', help_text='Column title under which this item is displayed (e.g., "COLLABORATIONS", "PARTNERS", "COMMUNITY")', max_length=100)),
                ('url', models.URLField(blank=True, help_text='Optional website or social link')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
                'ordering': ['order', 'name'],
            },
        ),
    ]
